package com.jcodee.demobackground.easy;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class PIIActorPncm extends AttributeContainer implements KvmSerializable
{
    
    public String ApellidoMaterno;
    
    public String ApellidoPaterno;
    
    public String DescripcionTipoActor;
    
    public String EmailCorporativo;
    
    public String FechaAlta;
    
    public String FechaBaja;
    
    public Long Id;
    
    public String Nombre;
    
    public String NumeroDocumento;
    
    public Long ServicioUnidadId;
    
    public Long SunidadApncmId;
    
    public Long TipoActor;
        
    private transient Object __source;
    

    
    
    public void loadFromSoap(Object paramObj, PIIExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,PIIExtendedSoapSerializationEnvelope __envelope)
    {
        Object obj = info.getValue();
        if (info.name.equals("ApellidoMaterno"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ApellidoMaterno = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ApellidoMaterno = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ApellidoPaterno"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ApellidoPaterno = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ApellidoPaterno = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DescripcionTipoActor"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DescripcionTipoActor = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.DescripcionTipoActor = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("EmailCorporativo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.EmailCorporativo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.EmailCorporativo = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("FechaAlta"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FechaAlta = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.FechaAlta = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("FechaBaja"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FechaBaja = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.FechaBaja = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Id"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Id = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.Id = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Nombre"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Nombre = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Nombre = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("NumeroDocumento"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.NumeroDocumento = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.NumeroDocumento = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ServicioUnidadId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ServicioUnidadId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.ServicioUnidadId = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SunidadApncmId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SunidadApncmId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.SunidadApncmId = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TipoActor"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TipoActor = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.TipoActor = (Long)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.ApellidoMaterno!=null?this.ApellidoMaterno:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.ApellidoPaterno!=null?this.ApellidoPaterno:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.DescripcionTipoActor!=null?this.DescripcionTipoActor:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.EmailCorporativo!=null?this.EmailCorporativo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.FechaAlta!=null?this.FechaAlta:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.FechaBaja!=null?this.FechaBaja:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.Id!=null?this.Id:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.Nombre!=null?this.Nombre:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.NumeroDocumento!=null?this.NumeroDocumento:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.ServicioUnidadId!=null?this.ServicioUnidadId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.SunidadApncmId!=null?this.SunidadApncmId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.TipoActor!=null?this.TipoActor:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 12;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ApellidoMaterno";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ApellidoPaterno";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DescripcionTipoActor";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "EmailCorporativo";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FechaAlta";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FechaBaja";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "Id";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Nombre";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "NumeroDocumento";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "ServicioUnidadId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "SunidadApncmId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "TipoActor";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}
