package com.jcodee.demobackground.easy;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class PIIComiteGestion extends AttributeContainer implements KvmSerializable
{
    
    public String CodigoUbigeo;
    
    public Integer EsPiloto;
    
    public String FechaCierre;
    
    public String FechaInicio;
    
    public Long Id;
    
    public String Nombre;
    
    public Long ProgramaUnidadId;
    
    public Long TComiteGestionId;
        
    private transient Object __source;
    

    
    
    public void loadFromSoap(Object paramObj, PIIExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,PIIExtendedSoapSerializationEnvelope __envelope)
    {
        Object obj = info.getValue();
        if (info.name.equals("CodigoUbigeo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CodigoUbigeo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CodigoUbigeo = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("EsPiloto"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.EsPiloto = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.EsPiloto = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("FechaCierre"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FechaCierre = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.FechaCierre = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("FechaInicio"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FechaInicio = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.FechaInicio = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Id"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Id = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.Id = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Nombre"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Nombre = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Nombre = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ProgramaUnidadId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ProgramaUnidadId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.ProgramaUnidadId = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TComiteGestionId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TComiteGestionId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.TComiteGestionId = (Long)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.CodigoUbigeo!=null?this.CodigoUbigeo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.EsPiloto!=null?this.EsPiloto:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.FechaCierre!=null?this.FechaCierre:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.FechaInicio!=null?this.FechaInicio:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.Id!=null?this.Id:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.Nombre!=null?this.Nombre:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.ProgramaUnidadId!=null?this.ProgramaUnidadId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.TComiteGestionId!=null?this.TComiteGestionId:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 8;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CodigoUbigeo";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "EsPiloto";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FechaCierre";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FechaInicio";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "Id";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Nombre";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "ProgramaUnidadId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "TComiteGestionId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}
