package com.jcodee.demobackground.easy;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



import org.ksoap2.SoapEnvelope;
import org.ksoap2.serialization.*;
import org.kxml2.io.KXmlParser;
import org.kxml2.kdom.Element;
import org.xmlpull.v1.XmlPullParser;
import org.xmlpull.v1.XmlPullParserFactory;
import org.xmlpull.v1.XmlSerializer;

import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Vector;
import java.io.StringReader;
import java.io.StringWriter;

//If you have a compilation error here then you have to add a reference to ExKsoap2.jar to your project (you can find it in Libs folder in the generated zip file)
public class PIIExtendedSoapSerializationEnvelope extends com.easywsdl.exksoap2.serialization.ExSoapSerializationEnvelope {
    static HashMap< String, Class> classNames = new HashMap< String, Class>();
    
    static {
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros^^ProgramaUnidad",PIIProgramaUnidad.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros^^UnidadDepartamento",PIIUnidadDepartamento.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros^^ComiteGestion",PIIComiteGestion.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros^^ActorPncm",PIIActorPncm.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros^^ActorComunal",PIIActorComunal.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros^^Local",PIILocal.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros^^NinioUsuario",PIINinioUsuario.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros^^PersonaComunal",PIIPersonaComunal.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros^^ServicioAlimentario",PIIServicioAlimentario.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros^^CentroPoblado",PIICentroPoblado.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros^^ComiteActor",PIIComiteActor.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros^^Cargo",PIICargo.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Ubigeo^^Location",PIILocation.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Ubigeo^^UbigeoDistrito",PIIUbigeoDistrito.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo^^RespuestaComunal",PIIRespuestaComunal.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo^^IntegranteFamiliaSCD",PIIIntegranteFamiliaSCD.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo^^Ficha",PIIFicha.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo^^Seccion",PIISeccion.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo^^Pregunta",PIIPregunta.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo^^Opcion",PIIOpcion.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo^^RolFicha",PIIRolFicha.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo^^Parametro",PIIParametro.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo^^TamizajeAnemia",PIITamizajeAnemia.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo^^TamizajeAnemiaControl",PIITamizajeAnemiaControl.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global^^Response",PIIResponse.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global^^Persona",PIIPersona.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.CoreCuidadoDiurno.Logic.Dto^^SaludResponse",PIISaludResponse.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Base^^EntidadBase",PIIEntidadBase.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Seguridad^^Usuario",PIIUsuario.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Seguridad^^Menu",PIIMenu.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Seguridad^^Perfil",PIIPerfil.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros^^ArrayOfProgramaUnidad",PIIArrayOfProgramaUnidad.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros^^ArrayOfUnidadDepartamento",PIIArrayOfUnidadDepartamento.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros^^ArrayOfComiteGestion",PIIArrayOfComiteGestion.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros^^ArrayOfActorPncm",PIIArrayOfActorPncm.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros^^ArrayOfActorComunal",PIIArrayOfActorComunal.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros^^ArrayOfLocal",PIIArrayOfLocal.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros^^ArrayOfNinioUsuario",PIIArrayOfNinioUsuario.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros^^ArrayOfPersonaComunal",PIIArrayOfPersonaComunal.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros^^ArrayOfServicioAlimentario",PIIArrayOfServicioAlimentario.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros^^ArrayOfCentroPoblado",PIIArrayOfCentroPoblado.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros^^ArrayOfComiteActor",PIIArrayOfComiteActor.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros^^ArrayOfCargo",PIIArrayOfCargo.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Ubigeo^^ArrayOfUbigeoDistrito",PIIArrayOfUbigeoDistrito.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo^^ArrayOfIntegranteFamiliaSCD",PIIArrayOfIntegranteFamiliaSCD.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo^^ArrayOfFicha",PIIArrayOfFicha.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo^^ArrayOfSeccion",PIIArrayOfSeccion.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo^^ArrayOfPregunta",PIIArrayOfPregunta.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo^^ArrayOfOpcion",PIIArrayOfOpcion.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo^^ArrayOfRolFicha",PIIArrayOfRolFicha.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo^^ArrayOfParametro",PIIArrayOfParametro.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo^^ArrayOfTamizajeAnemia",PIIArrayOfTamizajeAnemia.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo^^ArrayOfTamizajeAnemiaControl",PIIArrayOfTamizajeAnemiaControl.class);
        classNames.put("http://schemas.microsoft.com/2003/10/Serialization/Arrays^^ArrayOflong",PIIArrayOflong.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Seguridad^^ArrayOfMenu",PIIArrayOfMenu.class);
        classNames.put("http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Seguridad^^ArrayOfPerfil",PIIArrayOfPerfil.class);
    } 

    protected static final int QNAME_NAMESPACE = 0;
    private static final String TYPE_LABEL = "type";

    public PIIExtendedSoapSerializationEnvelope() {
        this(SoapEnvelope.VER11);
    }

    public PIIExtendedSoapSerializationEnvelope(int soapVersion) {
        super(soapVersion);
        implicitTypes = true;
        setAddAdornments(false);
        new PIIMarshalGuid().register(this);
        new MarshalFloat().register(this);
    }


    @Override
    protected void writeProperty(XmlSerializer writer, Object obj, PropertyInfo type) throws IOException {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if (obj == null || obj== SoapPrimitive.NullNilElement) {
            writer.attribute(xsi, version >= VER12 ? NIL_LABEL : NULL_LABEL, "true");
            return;
        }
        if(writeReferenceObject(writer,obj))
        {
            return;
        }
        Object[] qName = getInfo(null, obj);
        if (!type.multiRef && qName[2] == null )
        {
            if (!implicitTypes || (obj.getClass() != type.type && !(obj instanceof Vector ) && type.type!= String.class  )) {
                String xmlName=PIIHelper.getKeyByValue(classNames,obj.getClass());
                if(xmlName!=null) {
                    String[] parts = xmlName.split("\\^\\^");
                    String prefix = writer.getPrefix(parts[0], true);
                    writer.attribute(xsi, TYPE_LABEL, prefix + ":" + parts[1]);
                }
                else
                {
                    if(type.type instanceof String) {
                        String xsdPrefix = writer.getPrefix(xsd, true);
                        String myType = (String) type.type;
                        String[] parts = myType.split("\\^\\^");
                        if (parts.length == 2) {
                            xsdPrefix = writer.getPrefix(parts[0], true);
                            myType = parts[1];
                        }

                        writer.attribute(xsi, TYPE_LABEL, xsdPrefix + ":" + myType);
                    }
                    else
                    {
                        String prefix = writer.getPrefix(type.namespace, true);
                        writer.attribute(xsi, TYPE_LABEL, prefix + ":" + obj.getClass().getSimpleName());
                    }

                }
            }
            //super.writeProperty(writer,obj,type);

            //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
            //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
            writeElement(writer, obj, type, qName[QNAME_MARSHAL]);
        }
        else {
            super.writeProperty(writer, obj, type);
        }
    }

    public SoapObject GetExceptionDetail(Element detailElement, String exceptionElementNS, String exceptionElementName)
    {
        int index=detailElement.indexOf(exceptionElementNS,exceptionElementName,0);
        if(index>-1)
        {
            Element errorElement=detailElement.getElement(index);
            return GetSoapObject(errorElement);
        }
        return null;
    }

    public SoapObject GetSoapObject(Element detailElement) {
        try{
            XmlSerializer xmlSerializer = XmlPullParserFactory.newInstance().newSerializer();
            StringWriter writer = new StringWriter();
            xmlSerializer.setOutput(writer);
            detailElement.write(xmlSerializer);
            xmlSerializer.flush();

            XmlPullParser xpp = new KXmlParser();
            xpp.setFeature(XmlPullParser.FEATURE_PROCESS_NAMESPACES, true);

            xpp.setInput(new StringReader(writer.toString()));
            xpp.nextTag();
            SoapObject soapObj = new SoapObject(detailElement.getNamespace(),detailElement.getName());
            readSerializable(xpp,soapObj);
            return soapObj;
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
        }
        return null;
    }

    public Object GetHeader(Element detailElement) {
        if(detailElement.getChildCount()>0 && detailElement.getText(0)!=null)
        {
            SoapPrimitive primitive = new SoapPrimitive(detailElement.getNamespace(),detailElement.getName(),detailElement.getText(0));
            return  primitive;
        }
    
        return GetSoapObject(detailElement);
    }
    private Object createObject(Object soap, Class cl) throws InstantiationException, IllegalAccessException, NoSuchMethodException, InvocationTargetException {
        Object obj=cl.newInstance();
        Method ctor = obj.getClass().getMethod("loadFromSoap",Object.class,PIIExtendedSoapSerializationEnvelope.class);
        ctor.invoke(obj,soap,this);
        return obj;
    }

    public Object get(Object soap, Class cl, boolean typeFromClass)
    {
        if(soap==null)
        {
            return null;
        }
        try
        {
            if(typeFromClass)
            {
                return createObject(soap, cl);
            }
            Object refAttr=getReference(soap);
            if (refAttr != null)
            {
                return refAttr;
            }
            else
            {
                if(soap instanceof SoapObject)
                {
                    if(cl ==SoapObject.class)
                    {
                        return soap;
                    }
                    String key=String.format("%s^^%s",((SoapObject)soap).getNamespace(),((SoapObject)soap).getName());
                    if(classNames.containsKey(key))
                    {
                        cl=classNames.get(key);
                    }
                }
                return createObject(soap, cl);
            }
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
            return null;
        }
    }


    public Object getSpecificType(Object obj)
    {
        if(obj==null)
        {
            return null;
        }
        if(obj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)obj;
            String key=soapObject.getNamespace()+"^^"+soapObject.getName();
            if(classNames.containsKey(key))
            {
                Class cl=classNames.get(key);
                try
                {
                    return createObject(soapObject, cl);
                } 
                catch (Exception e)
                {
                    e.printStackTrace();
                }
            }
        }

        return obj;
    }

    public static Object getXSDType(Object param)
    {
        if(param==null)
        {
            return null;
        }
        Class obj=param.getClass();
        if(obj.equals(String.class))
        {
            return "string";
        }
        if(obj.equals(int.class) || obj.equals(Integer.class))
        {
            return "int";
        }
        if(obj.equals(float.class) || obj.equals(Float.class))
        {
            return "float";
        }
        if(obj.equals(double.class) || obj.equals(Double.class))
        {
            return "double";
        }
        if(obj.equals(java.math.BigDecimal.class))
        {
            return "decimal";
        }
        if(obj.equals(short.class) || obj.equals(Short.class))
        {
            return "short";
        }
        if(obj.equals(long.class) || obj.equals(Long.class))
        {
            return "long";
        }
        if(obj.equals(boolean.class) || obj.equals(Boolean.class))
        {
            return "boolean";
        }
        String xmlName=PIIHelper.getKeyByValue(classNames,obj);
        if(xmlName==null)
        {
            return obj;
        }
        return xmlName;
    }} 

