package com.jcodee.demobackground.easy;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class PIIEntidadBase extends AttributeContainer implements KvmSerializable
{
    
    public Boolean Activa;
    
    public java.util.Date FechaModificacion;
    
    public java.util.Date FechaRegistro;
    
    public Long Id;
    
    public String UsuarioModificacion;
    
    public String UsuarioRegistro;
        
    private transient Object __source;
    

    
    
    public void loadFromSoap(Object paramObj, PIIExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,PIIExtendedSoapSerializationEnvelope __envelope)
    {
        Object obj = info.getValue();
        if (info.name.equals("Activa"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Activa = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.Activa = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("FechaModificacion"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FechaModificacion = PIIHelper.ConvertFromWebService(j.toString());
                    }
                }
                else if (obj instanceof java.util.Date){
                    this.FechaModificacion = (java.util.Date)obj;
                }
            }
            return true;
        }
        if (info.name.equals("FechaRegistro"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FechaRegistro = PIIHelper.ConvertFromWebService(j.toString());
                    }
                }
                else if (obj instanceof java.util.Date){
                    this.FechaRegistro = (java.util.Date)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Id"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Id = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.Id = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("UsuarioModificacion"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.UsuarioModificacion = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.UsuarioModificacion = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("UsuarioRegistro"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.UsuarioRegistro = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.UsuarioRegistro = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Activa!=null?this.Activa:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.FechaModificacion!=null?PIIHelper.getDateTimeFormat().format(this.FechaModificacion):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.FechaRegistro!=null?PIIHelper.getDateTimeFormat().format(this.FechaRegistro):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.Id!=null?this.Id:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.UsuarioModificacion!=null?this.UsuarioModificacion:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.UsuarioRegistro!=null?this.UsuarioRegistro:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "Activa";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Base";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FechaModificacion";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Base";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FechaRegistro";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Base";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "Id";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Base";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "UsuarioModificacion";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Base";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "UsuarioRegistro";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Base";
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}
