package com.jcodee.demobackground.easy;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class PIIFicha extends AttributeContainer implements KvmSerializable
{
    
    public String Acronimo;
    
    public Long EsMultipart;
    
    public Integer Especicifica;
    
    public String Grupo;
    
    public Long GuardaComite;
    
    public Long GuardaFechaVisita;
    
    public Long GuardaPreguntas;
    
    public Long GuardaUbigeo;
    
    public Long Id;
    
    public Integer MuestraResultado;
    
    public Integer MuestraResumen;
    
    public String Nombre;
    
    public String NombreImagen;
    
    public Long Orden;
    
    public Long ServicioId;
    
    public Integer UbicacionObligatorio;
    
    public Integer UsaFormulas;
    
    public Long ValorAdicional;
        
    private transient Object __source;
    

    
    
    public void loadFromSoap(Object paramObj, PIIExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,PIIExtendedSoapSerializationEnvelope __envelope)
    {
        Object obj = info.getValue();
        if (info.name.equals("Acronimo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Acronimo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Acronimo = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("EsMultipart"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.EsMultipart = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.EsMultipart = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Especicifica"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Especicifica = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.Especicifica = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Grupo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Grupo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Grupo = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("GuardaComite"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.GuardaComite = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.GuardaComite = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("GuardaFechaVisita"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.GuardaFechaVisita = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.GuardaFechaVisita = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("GuardaPreguntas"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.GuardaPreguntas = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.GuardaPreguntas = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("GuardaUbigeo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.GuardaUbigeo = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.GuardaUbigeo = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Id"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Id = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.Id = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("MuestraResultado"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MuestraResultado = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.MuestraResultado = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("MuestraResumen"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MuestraResumen = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.MuestraResumen = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Nombre"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Nombre = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Nombre = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("NombreImagen"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.NombreImagen = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.NombreImagen = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Orden"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Orden = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.Orden = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ServicioId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ServicioId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.ServicioId = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("UbicacionObligatorio"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.UbicacionObligatorio = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.UbicacionObligatorio = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("UsaFormulas"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.UsaFormulas = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.UsaFormulas = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ValorAdicional"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ValorAdicional = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.ValorAdicional = (Long)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Acronimo!=null?this.Acronimo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.EsMultipart!=null?this.EsMultipart:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.Especicifica!=null?this.Especicifica:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.Grupo!=null?this.Grupo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.GuardaComite!=null?this.GuardaComite:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.GuardaFechaVisita!=null?this.GuardaFechaVisita:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.GuardaPreguntas!=null?this.GuardaPreguntas:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.GuardaUbigeo!=null?this.GuardaUbigeo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.Id!=null?this.Id:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.MuestraResultado!=null?this.MuestraResultado:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.MuestraResumen!=null?this.MuestraResumen:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.Nombre!=null?this.Nombre:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==12)
        {
            return this.NombreImagen!=null?this.NombreImagen:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==13)
        {
            return this.Orden!=null?this.Orden:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==14)
        {
            return this.ServicioId!=null?this.ServicioId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==15)
        {
            return this.UbicacionObligatorio!=null?this.UbicacionObligatorio:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==16)
        {
            return this.UsaFormulas!=null?this.UsaFormulas:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==17)
        {
            return this.ValorAdicional!=null?this.ValorAdicional:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 18;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Acronimo";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "EsMultipart";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "Especicifica";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Grupo";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "GuardaComite";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "GuardaFechaVisita";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "GuardaPreguntas";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "GuardaUbigeo";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "Id";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "MuestraResultado";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "MuestraResumen";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Nombre";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "NombreImagen";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "Orden";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==14)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "ServicioId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==15)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "UbicacionObligatorio";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==16)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "UsaFormulas";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==17)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "ValorAdicional";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}
