package com.jcodee.demobackground.easy;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class PIIIntegranteFamiliaSCD extends AttributeContainer implements KvmSerializable
{
    
    public Long HogarId;
    
    public Long Id;
    
    public String NombreCompletpo;
    
    public String Parantesco;
    
    public Long TLocalId;
    
    public String TipoParentesco;
        
    private transient Object __source;
    

    
    
    public void loadFromSoap(Object paramObj, PIIExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,PIIExtendedSoapSerializationEnvelope __envelope)
    {
        Object obj = info.getValue();
        if (info.name.equals("HogarId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.HogarId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.HogarId = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Id"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Id = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.Id = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("NombreCompletpo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.NombreCompletpo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.NombreCompletpo = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Parantesco"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Parantesco = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Parantesco = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TLocalId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TLocalId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.TLocalId = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TipoParentesco"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TipoParentesco = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.TipoParentesco = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.HogarId!=null?this.HogarId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.Id!=null?this.Id:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.NombreCompletpo!=null?this.NombreCompletpo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.Parantesco!=null?this.Parantesco:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.TLocalId!=null?this.TLocalId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.TipoParentesco!=null?this.TipoParentesco:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "HogarId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "Id";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "NombreCompletpo";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Parantesco";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "TLocalId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TipoParentesco";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}
