package com.jcodee.demobackground.easy;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



public interface PIIIServiceEvents
{
    void Starting();
    void Completed(PIIOperationResult result);
}
