package com.jcodee.demobackground.easy;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class PIILocal extends AttributeContainer implements KvmSerializable
{
    
    public Long CentroPobladoId;
    
    public Long ComiteGestionId;
    
    public String Direccion;
    
    public Integer EsPiloto;
    
    public Integer EsReferenciado;
    
    public String Estado;
    
    public Long Id;
    
    public String Nombre;
    
    public String Referencia;
    
    public Long TLocalId;
    
    public String TipoLocal;
        
    private transient Object __source;
    

    
    
    public void loadFromSoap(Object paramObj, PIIExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,PIIExtendedSoapSerializationEnvelope __envelope)
    {
        Object obj = info.getValue();
        if (info.name.equals("CentroPobladoId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CentroPobladoId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.CentroPobladoId = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ComiteGestionId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ComiteGestionId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.ComiteGestionId = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Direccion"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Direccion = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Direccion = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("EsPiloto"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.EsPiloto = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.EsPiloto = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("EsReferenciado"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.EsReferenciado = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.EsReferenciado = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Estado"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Estado = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Estado = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Id"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Id = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.Id = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Nombre"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Nombre = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Nombre = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Referencia"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Referencia = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Referencia = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TLocalId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TLocalId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.TLocalId = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TipoLocal"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TipoLocal = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.TipoLocal = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.CentroPobladoId!=null?this.CentroPobladoId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.ComiteGestionId!=null?this.ComiteGestionId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.Direccion!=null?this.Direccion:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.EsPiloto!=null?this.EsPiloto:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.EsReferenciado!=null?this.EsReferenciado:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.Estado!=null?this.Estado:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.Id!=null?this.Id:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.Nombre!=null?this.Nombre:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.Referencia!=null?this.Referencia:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.TLocalId!=null?this.TLocalId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.TipoLocal!=null?this.TipoLocal:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 11;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "CentroPobladoId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "ComiteGestionId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Direccion";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "EsPiloto";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "EsReferenciado";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Estado";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "Id";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Nombre";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Referencia";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "TLocalId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TipoLocal";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}
