package com.jcodee.demobackground.easy;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class PIINinioUsuario extends AttributeContainer implements KvmSerializable
{
    
    public Long AnioAsistencia;
    
    public String ApellidoMaterno;
    
    public String ApellidoPaterno;
    
    public String CodigoCentroPoblado;
    
    public String CodigoUbigeo;
    
    public Long CuidadorPrincipalId;
    
    public String Discapacidad;
    
    public Integer EsCuidadorPrincipal;
    
    public Integer EsGestante;
    
    public Integer EsReferenciada;
    
    public Long FacilitadorId;
    
    public Long FamiliaId;
    
    public String FechaIngreso;
    
    public String FechaNacimiento;
    
    public Long Id;
    
    public Long LocalId;
    
    public Long MesAsistencia;
    
    public Long MesesGestacion;
    
    public String Nombre;
    
    public String NombreCompletoCuidador;
    
    public String NombreCompletoFacilitador;
    
    public String NumeroDocumento;
    
    public String Parentesco;
    
    public Long ServicioUnidadId;
    
    public Integer Sexo;
    
    public Long TCentroPobladoId;
    
    public Long TComiteGestionId;
    
    public Long TModuloId;
    
    public Long TSalaPadreId;
    
    public Long TipoParentesco;
    
    public String TipoSala;
    
    public String TipoSeguroSalud;
    
    public Long TlocalId;
        
    private transient Object __source;
    

    
    
    public void loadFromSoap(Object paramObj, PIIExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,PIIExtendedSoapSerializationEnvelope __envelope)
    {
        Object obj = info.getValue();
        if (info.name.equals("AnioAsistencia"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.AnioAsistencia = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.AnioAsistencia = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ApellidoMaterno"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ApellidoMaterno = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ApellidoMaterno = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ApellidoPaterno"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ApellidoPaterno = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ApellidoPaterno = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("CodigoCentroPoblado"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CodigoCentroPoblado = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CodigoCentroPoblado = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("CodigoUbigeo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CodigoUbigeo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CodigoUbigeo = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("CuidadorPrincipalId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CuidadorPrincipalId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.CuidadorPrincipalId = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Discapacidad"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Discapacidad = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Discapacidad = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("EsCuidadorPrincipal"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.EsCuidadorPrincipal = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.EsCuidadorPrincipal = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("EsGestante"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.EsGestante = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.EsGestante = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("EsReferenciada"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.EsReferenciada = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.EsReferenciada = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("FacilitadorId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FacilitadorId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.FacilitadorId = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("FamiliaId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FamiliaId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.FamiliaId = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("FechaIngreso"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FechaIngreso = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.FechaIngreso = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("FechaNacimiento"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FechaNacimiento = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.FechaNacimiento = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Id"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Id = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.Id = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("LocalId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.LocalId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.LocalId = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("MesAsistencia"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MesAsistencia = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.MesAsistencia = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("MesesGestacion"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MesesGestacion = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.MesesGestacion = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Nombre"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Nombre = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Nombre = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("NombreCompletoCuidador"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.NombreCompletoCuidador = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.NombreCompletoCuidador = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("NombreCompletoFacilitador"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.NombreCompletoFacilitador = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.NombreCompletoFacilitador = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("NumeroDocumento"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.NumeroDocumento = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.NumeroDocumento = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Parentesco"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Parentesco = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Parentesco = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ServicioUnidadId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ServicioUnidadId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.ServicioUnidadId = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Sexo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Sexo = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.Sexo = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TCentroPobladoId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TCentroPobladoId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.TCentroPobladoId = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TComiteGestionId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TComiteGestionId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.TComiteGestionId = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TModuloId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TModuloId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.TModuloId = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TSalaPadreId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TSalaPadreId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.TSalaPadreId = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TipoParentesco"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TipoParentesco = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.TipoParentesco = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TipoSala"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TipoSala = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.TipoSala = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TipoSeguroSalud"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TipoSeguroSalud = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.TipoSeguroSalud = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TlocalId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TlocalId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.TlocalId = (Long)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.AnioAsistencia!=null?this.AnioAsistencia:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.ApellidoMaterno!=null?this.ApellidoMaterno:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.ApellidoPaterno!=null?this.ApellidoPaterno:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.CodigoCentroPoblado!=null?this.CodigoCentroPoblado:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.CodigoUbigeo!=null?this.CodigoUbigeo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.CuidadorPrincipalId!=null?this.CuidadorPrincipalId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.Discapacidad!=null?this.Discapacidad:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.EsCuidadorPrincipal!=null?this.EsCuidadorPrincipal:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.EsGestante!=null?this.EsGestante:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.EsReferenciada!=null?this.EsReferenciada:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.FacilitadorId!=null?this.FacilitadorId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.FamiliaId!=null?this.FamiliaId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==12)
        {
            return this.FechaIngreso!=null?this.FechaIngreso:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==13)
        {
            return this.FechaNacimiento!=null?this.FechaNacimiento:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==14)
        {
            return this.Id!=null?this.Id:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==15)
        {
            return this.LocalId!=null?this.LocalId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==16)
        {
            return this.MesAsistencia!=null?this.MesAsistencia:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==17)
        {
            return this.MesesGestacion!=null?this.MesesGestacion:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==18)
        {
            return this.Nombre!=null?this.Nombre:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==19)
        {
            return this.NombreCompletoCuidador!=null?this.NombreCompletoCuidador:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==20)
        {
            return this.NombreCompletoFacilitador!=null?this.NombreCompletoFacilitador:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==21)
        {
            return this.NumeroDocumento!=null?this.NumeroDocumento:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==22)
        {
            return this.Parentesco!=null?this.Parentesco:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==23)
        {
            return this.ServicioUnidadId!=null?this.ServicioUnidadId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==24)
        {
            return this.Sexo!=null?this.Sexo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==25)
        {
            return this.TCentroPobladoId!=null?this.TCentroPobladoId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==26)
        {
            return this.TComiteGestionId!=null?this.TComiteGestionId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==27)
        {
            return this.TModuloId!=null?this.TModuloId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==28)
        {
            return this.TSalaPadreId!=null?this.TSalaPadreId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==29)
        {
            return this.TipoParentesco!=null?this.TipoParentesco:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==30)
        {
            return this.TipoSala!=null?this.TipoSala:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==31)
        {
            return this.TipoSeguroSalud!=null?this.TipoSeguroSalud:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==32)
        {
            return this.TlocalId!=null?this.TlocalId:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 33;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "AnioAsistencia";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ApellidoMaterno";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ApellidoPaterno";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CodigoCentroPoblado";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CodigoUbigeo";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "CuidadorPrincipalId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Discapacidad";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "EsCuidadorPrincipal";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "EsGestante";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "EsReferenciada";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "FacilitadorId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "FamiliaId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FechaIngreso";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FechaNacimiento";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==14)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "Id";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==15)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "LocalId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==16)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "MesAsistencia";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==17)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "MesesGestacion";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==18)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Nombre";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==19)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "NombreCompletoCuidador";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==20)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "NombreCompletoFacilitador";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==21)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "NumeroDocumento";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==22)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Parentesco";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==23)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "ServicioUnidadId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==24)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "Sexo";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==25)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "TCentroPobladoId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==26)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "TComiteGestionId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==27)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "TModuloId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==28)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "TSalaPadreId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==29)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "TipoParentesco";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==30)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TipoSala";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==31)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TipoSeguroSalud";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==32)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "TlocalId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}
