package com.jcodee.demobackground.easy;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



public class PIIOperationResult< T>
{
    public java.lang.Exception Exception;
    public T Result;
    public Object Tag;
    public String MethodName;
}
