package com.jcodee.demobackground.easy;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class PIIProgramaUnidad extends AttributeContainer implements KvmSerializable
{
    
    public String CodigoUbigeoOficina;
    
    public String CodigoUnidad;
    
    public String Departamento;
    
    public String Direccion;
    
    public String DireccionImagen;
    
    public String Distrito;
    
    public Long Id;
    
    public PIILocation Location;
    
    public String NombrePrograma;
    
    public String NombreUnidadTerritorial;
    
    public Long ProgramaId;
    
    public String Provincia;
    
    public String Referencia;
    
    public Long UnidadTerritorialId;
        
    private transient Object __source;
    

    
    
    public void loadFromSoap(Object paramObj, PIIExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,PIIExtendedSoapSerializationEnvelope __envelope)
    {
        Object obj = info.getValue();
        if (info.name.equals("CodigoUbigeoOficina"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CodigoUbigeoOficina = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CodigoUbigeoOficina = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("CodigoUnidad"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CodigoUnidad = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CodigoUnidad = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Departamento"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Departamento = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Departamento = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Direccion"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Direccion = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Direccion = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DireccionImagen"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DireccionImagen = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.DireccionImagen = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Distrito"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Distrito = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Distrito = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Id"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Id = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.Id = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Location"))
        {
            if(obj!=null)
            {
                Object j = obj;
                this.Location = (PIILocation)__envelope.get(j,PIILocation.class,false);
            }
            return true;
        }
        if (info.name.equals("NombrePrograma"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.NombrePrograma = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.NombrePrograma = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("NombreUnidadTerritorial"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.NombreUnidadTerritorial = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.NombreUnidadTerritorial = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ProgramaId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ProgramaId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.ProgramaId = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Provincia"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Provincia = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Provincia = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Referencia"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Referencia = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Referencia = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("UnidadTerritorialId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.UnidadTerritorialId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.UnidadTerritorialId = (Long)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.CodigoUbigeoOficina!=null?this.CodigoUbigeoOficina:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.CodigoUnidad!=null?this.CodigoUnidad:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.Departamento!=null?this.Departamento:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.Direccion!=null?this.Direccion:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.DireccionImagen!=null?this.DireccionImagen:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.Distrito!=null?this.Distrito:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.Id!=null?this.Id:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.Location!=null?this.Location:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.NombrePrograma!=null?this.NombrePrograma:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.NombreUnidadTerritorial!=null?this.NombreUnidadTerritorial:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.ProgramaId!=null?this.ProgramaId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.Provincia!=null?this.Provincia:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==12)
        {
            return this.Referencia!=null?this.Referencia:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==13)
        {
            return this.UnidadTerritorialId!=null?this.UnidadTerritorialId:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 14;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CodigoUbigeoOficina";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CodigoUnidad";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Departamento";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Direccion";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DireccionImagen";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Distrito";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "Id";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==7)
        {
            info.type = PIILocation.class;
            info.name = "Location";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "NombrePrograma";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "NombreUnidadTerritorial";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "ProgramaId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Provincia";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Referencia";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "UnidadTerritorialId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}
