package com.jcodee.demobackground.easy;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class PIIPregunta extends AttributeContainer implements KvmSerializable
{
    
    public String Descripcion;
    
    public String Discriminador;
    
    public Long Id;
    
    public Integer Obligatorio;
    
    public Long Orden;
    
    public Long Principal;
    
    public Long SeccionId;
    
    public String TecnicaAplicacion;
    
    public Long TipoPregunta;
        
    private transient Object __source;
    

    
    
    public void loadFromSoap(Object paramObj, PIIExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,PIIExtendedSoapSerializationEnvelope __envelope)
    {
        Object obj = info.getValue();
        if (info.name.equals("Descripcion"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Descripcion = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Descripcion = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Discriminador"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Discriminador = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Discriminador = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Id"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Id = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.Id = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Obligatorio"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Obligatorio = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.Obligatorio = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Orden"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Orden = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.Orden = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Principal"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Principal = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.Principal = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SeccionId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SeccionId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.SeccionId = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TecnicaAplicacion"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TecnicaAplicacion = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.TecnicaAplicacion = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TipoPregunta"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TipoPregunta = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.TipoPregunta = (Long)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Descripcion!=null?this.Descripcion:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.Discriminador!=null?this.Discriminador:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.Id!=null?this.Id:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.Obligatorio!=null?this.Obligatorio:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.Orden!=null?this.Orden:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.Principal!=null?this.Principal:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.SeccionId!=null?this.SeccionId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.TecnicaAplicacion!=null?this.TecnicaAplicacion:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.TipoPregunta!=null?this.TipoPregunta:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 9;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Descripcion";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Discriminador";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "Id";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "Obligatorio";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "Orden";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "Principal";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "SeccionId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TecnicaAplicacion";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "TipoPregunta";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}
