package com.jcodee.demobackground.easy;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class PIIPersona extends PIIEntidadBase implements KvmSerializable
{
    
    public String ApellidoMaterno;
    
    public String ApellidoPaterno;
    
    public String EMail;
    
    public String Nombre;
    
    public String NombreCompleto;
    
    public String NumeroDocumento;
        

    
    
    @Override
    public void loadFromSoap(Object paramObj, PIIExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        super.loadFromSoap(paramObj, __envelope);



    }

    @Override
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,PIIExtendedSoapSerializationEnvelope __envelope)
    {
        Object obj = info.getValue();
        if (info.name.equals("ApellidoMaterno"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ApellidoMaterno = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ApellidoMaterno = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ApellidoPaterno"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ApellidoPaterno = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ApellidoPaterno = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("EMail"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.EMail = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.EMail = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Nombre"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Nombre = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Nombre = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("NombreCompleto"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.NombreCompleto = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.NombreCompleto = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("NumeroDocumento"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.NumeroDocumento = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.NumeroDocumento = (String)obj;
                }
            }
            return true;
        }
        return super.loadProperty(info,soapObject,__envelope);
    }
    
    

    @Override
    public Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return this.ApellidoMaterno!=null?this.ApellidoMaterno:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+1)
        {
            return this.ApellidoPaterno!=null?this.ApellidoPaterno:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+2)
        {
            return this.EMail!=null?this.EMail:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+3)
        {
            return this.Nombre!=null?this.Nombre:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+4)
        {
            return this.NombreCompleto!=null?this.NombreCompleto:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+5)
        {
            return this.NumeroDocumento!=null?this.NumeroDocumento:SoapPrimitive.NullSkip;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ApellidoMaterno";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global";
        }
        if(propertyIndex==count+1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ApellidoPaterno";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global";
        }
        if(propertyIndex==count+2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "EMail";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global";
        }
        if(propertyIndex==count+3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Nombre";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global";
        }
        if(propertyIndex==count+4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "NombreCompleto";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global";
        }
        if(propertyIndex==count+5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "NumeroDocumento";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }

    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}
