package com.jcodee.demobackground.easy;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class PIIPersonaComunal extends AttributeContainer implements KvmSerializable
{
    
    public String ApellidoMaterno;
    
    public String ApellidoPaterno;
    
    public Long ComiteGestionId;
    
    public String Estado;
    
    public Long Id;
    
    public Long LocalId;
    
    public String NombreCompleto;
    
    public String Nombres;
    
    public String NumeroDocumento;
    
    public Long SalaId;
    
    public Long TComiteGestionId;
    
    public String TipoGuia;
        
    private transient Object __source;
    

    
    
    public void loadFromSoap(Object paramObj, PIIExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,PIIExtendedSoapSerializationEnvelope __envelope)
    {
        Object obj = info.getValue();
        if (info.name.equals("ApellidoMaterno"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ApellidoMaterno = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ApellidoMaterno = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ApellidoPaterno"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ApellidoPaterno = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ApellidoPaterno = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ComiteGestionId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ComiteGestionId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.ComiteGestionId = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Estado"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Estado = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Estado = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Id"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Id = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.Id = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("LocalId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.LocalId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.LocalId = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("NombreCompleto"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.NombreCompleto = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.NombreCompleto = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Nombres"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Nombres = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Nombres = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("NumeroDocumento"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.NumeroDocumento = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.NumeroDocumento = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SalaId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SalaId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.SalaId = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TComiteGestionId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TComiteGestionId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.TComiteGestionId = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TipoGuia"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TipoGuia = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.TipoGuia = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.ApellidoMaterno!=null?this.ApellidoMaterno:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.ApellidoPaterno!=null?this.ApellidoPaterno:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.ComiteGestionId!=null?this.ComiteGestionId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.Estado!=null?this.Estado:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.Id!=null?this.Id:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.LocalId!=null?this.LocalId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.NombreCompleto!=null?this.NombreCompleto:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.Nombres!=null?this.Nombres:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.NumeroDocumento!=null?this.NumeroDocumento:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.SalaId!=null?this.SalaId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.TComiteGestionId!=null?this.TComiteGestionId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.TipoGuia!=null?this.TipoGuia:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 12;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ApellidoMaterno";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ApellidoPaterno";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "ComiteGestionId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Estado";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "Id";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "LocalId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "NombreCompleto";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Nombres";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "NumeroDocumento";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "SalaId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "TComiteGestionId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TipoGuia";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Maestros";
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}
