package com.jcodee.demobackground.easy;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class PIIRespuestaComunal extends AttributeContainer implements KvmSerializable
{
    
    public PIIArrayOflong IdsComiteGestion;
    
    public PIIArrayOflong IdsLocal;
    
    public PIIArrayOflong IdsServicioUnidad;
    
    public PIIArrayOfIntegranteFamiliaSCD Integrantes;
    
    public PIIArrayOfNinioUsuario NiniosUsuarios;
    
    public PIIArrayOfPersonaComunal Voluntarios;
        
    private transient Object __source;
    

    
    
    public void loadFromSoap(Object paramObj, PIIExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,PIIExtendedSoapSerializationEnvelope __envelope)
    {
        Object obj = info.getValue();
        if (info.name.equals("IdsComiteGestion"))
        {
            if(obj!=null)
            {
                Object j = obj;
                this.IdsComiteGestion = (PIIArrayOflong)__envelope.get(j,PIIArrayOflong.class,false);
            }
            return true;
        }
        if (info.name.equals("IdsLocal"))
        {
            if(obj!=null)
            {
                Object j = obj;
                this.IdsLocal = (PIIArrayOflong)__envelope.get(j,PIIArrayOflong.class,false);
            }
            return true;
        }
        if (info.name.equals("IdsServicioUnidad"))
        {
            if(obj!=null)
            {
                Object j = obj;
                this.IdsServicioUnidad = (PIIArrayOflong)__envelope.get(j,PIIArrayOflong.class,false);
            }
            return true;
        }
        if (info.name.equals("Integrantes"))
        {
            if(obj!=null)
            {
                Object j = obj;
                this.Integrantes = (PIIArrayOfIntegranteFamiliaSCD)__envelope.get(j,PIIArrayOfIntegranteFamiliaSCD.class,false);
            }
            return true;
        }
        if (info.name.equals("NiniosUsuarios"))
        {
            if(obj!=null)
            {
                Object j = obj;
                this.NiniosUsuarios = (PIIArrayOfNinioUsuario)__envelope.get(j,PIIArrayOfNinioUsuario.class,false);
            }
            return true;
        }
        if (info.name.equals("Voluntarios"))
        {
            if(obj!=null)
            {
                Object j = obj;
                this.Voluntarios = (PIIArrayOfPersonaComunal)__envelope.get(j,PIIArrayOfPersonaComunal.class,false);
            }
            return true;
        }
        return false;
    }
    
    public Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.IdsComiteGestion!=null?this.IdsComiteGestion:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.IdsLocal!=null?this.IdsLocal:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.IdsServicioUnidad!=null?this.IdsServicioUnidad:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.Integrantes!=null?this.Integrantes:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.NiniosUsuarios!=null?this.NiniosUsuarios:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.Voluntarios!=null?this.Voluntarios:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "IdsComiteGestion";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "IdsLocal";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "IdsServicioUnidad";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "Integrantes";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "NiniosUsuarios";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "Voluntarios";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}
