package com.jcodee.demobackground.easy;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.math.BigDecimal;

public class PIITamizajeAnemia extends AttributeContainer implements KvmSerializable
{
    
    public String Diagnostico;
    
    public Long EdadExamen;
    
    public Integer Estado;
    
    public Long ExportacionId;
    
    public String FechaCrea;
    
    public String FechaExamen;
    
    public String FechaIniTratamiento;
    
    public String FechaModifica;
    
    public PIIArrayOfTamizajeAnemiaControl ListarAnemiaControls;
    
    public Long Periodo;
    
    public BigDecimal Valor;
        
    private transient Object __source;
    

    
    
    public void loadFromSoap(Object paramObj, PIIExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,PIIExtendedSoapSerializationEnvelope __envelope)
    {
        Object obj = info.getValue();
        if (info.name.equals("Diagnostico"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Diagnostico = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Diagnostico = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("EdadExamen"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.EdadExamen = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.EdadExamen = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Estado"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Estado = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.Estado = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ExportacionId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ExportacionId = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.ExportacionId = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("FechaCrea"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FechaCrea = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.FechaCrea = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("FechaExamen"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FechaExamen = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.FechaExamen = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("FechaIniTratamiento"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FechaIniTratamiento = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.FechaIniTratamiento = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("FechaModifica"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FechaModifica = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.FechaModifica = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ListarAnemiaControls"))
        {
            if(obj!=null)
            {
                Object j = obj;
                this.ListarAnemiaControls = (PIIArrayOfTamizajeAnemiaControl)__envelope.get(j,PIIArrayOfTamizajeAnemiaControl.class,false);
            }
            return true;
        }
        if (info.name.equals("Periodo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Periodo = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.Periodo = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Valor"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Valor = new BigDecimal(j.toString());
                    }
                }
                else if (obj instanceof BigDecimal){
                    this.Valor = (BigDecimal)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Diagnostico!=null?this.Diagnostico:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.EdadExamen!=null?this.EdadExamen:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.Estado!=null?this.Estado:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.ExportacionId!=null?this.ExportacionId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.FechaCrea!=null?this.FechaCrea:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.FechaExamen!=null?this.FechaExamen:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.FechaIniTratamiento!=null?this.FechaIniTratamiento:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.FechaModifica!=null?this.FechaModifica:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.ListarAnemiaControls!=null?this.ListarAnemiaControls:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.Periodo!=null?this.Periodo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.Valor!=null?this.Valor.toString():SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 11;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Diagnostico";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "EdadExamen";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "Estado";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "ExportacionId";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FechaCrea";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FechaExamen";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FechaIniTratamiento";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FechaModifica";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "ListarAnemiaControls";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "Periodo";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Valor";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.FichasMonitoreo";
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}
