package com.jcodee.demobackground.easy;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class PIIUbigeoDistrito extends AttributeContainer implements KvmSerializable
{
    
    public String CodigoDepartamento;
    
    public String CodigoDistrito;
    
    public String CodigoProvincia;
    
    public String CodigoUbigeo;
    
    public String Departamento;
    
    public String Distrito;
    
    public Long Id;
    
    public String Provincia;
        
    private transient Object __source;
    

    
    
    public void loadFromSoap(Object paramObj, PIIExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,PIIExtendedSoapSerializationEnvelope __envelope)
    {
        Object obj = info.getValue();
        if (info.name.equals("CodigoDepartamento"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CodigoDepartamento = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CodigoDepartamento = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("CodigoDistrito"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CodigoDistrito = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CodigoDistrito = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("CodigoProvincia"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CodigoProvincia = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CodigoProvincia = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("CodigoUbigeo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CodigoUbigeo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CodigoUbigeo = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Departamento"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Departamento = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Departamento = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Distrito"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Distrito = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Distrito = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Id"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Id = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.Id = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Provincia"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Provincia = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Provincia = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.CodigoDepartamento!=null?this.CodigoDepartamento:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.CodigoDistrito!=null?this.CodigoDistrito:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.CodigoProvincia!=null?this.CodigoProvincia:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.CodigoUbigeo!=null?this.CodigoUbigeo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.Departamento!=null?this.Departamento:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.Distrito!=null?this.Distrito:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.Id!=null?this.Id:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.Provincia!=null?this.Provincia:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 8;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CodigoDepartamento";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Ubigeo";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CodigoDistrito";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Ubigeo";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CodigoProvincia";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Ubigeo";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CodigoUbigeo";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Ubigeo";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Departamento";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Ubigeo";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Distrito";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Ubigeo";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "Id";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Ubigeo";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Provincia";
            info.namespace= "http://schemas.datacontract.org/2004/07/CunaMas.Component.Entities.Global.Ubigeo";
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}
